"""initial_schema

Revision ID: 6b1a34c39382
Revises: 
Create Date: 2026-07-06 23:04:39.533078

"""
import pgvector
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b1a34c39382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable vector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('filing_type', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_source_documents_filing_type'), 'source_documents', ['filing_type'], unique=False)
    op.create_index(op.f('ix_source_documents_fiscal_year'), 'source_documents', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_source_documents_ticker'), 'source_documents', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text_content)", persisted=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    # GIN index on full-text search vector
    op.create_index('ix_document_chunks_search_vector_gin', 'document_chunks', ['search_vector'], postgresql_using='gin')
    # GIN index on metadata JSONB
    op.create_index('ix_document_chunks_metadata_gin', 'document_chunks', ['metadata'], postgresql_using='gin')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_chunk_id'), 'message_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # HNSW Index for vector cosine similarity search
    op.execute("CREATE INDEX ix_document_chunks_embedding_hnsw ON document_chunks USING hnsw (embedding vector_cosine_ops);")

    # Row-Level Security (RLS) Enablement & Policies
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY user_self_policy ON users FOR ALL TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);")

    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY thread_user_policy ON chat_threads FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);")

    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY message_thread_user_policy ON chat_messages FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM chat_threads WHERE chat_threads.id = thread_id AND chat_threads.user_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM chat_threads WHERE chat_threads.id = thread_id AND chat_threads.user_id = auth.uid()));")

    op.execute("ALTER TABLE message_citations ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY citation_message_user_policy ON message_citations FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM chat_messages JOIN chat_threads ON chat_messages.thread_id = chat_threads.id WHERE chat_messages.id = message_id AND chat_threads.user_id = auth.uid()));")

    op.execute("ALTER TABLE source_documents ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY documents_read_policy ON source_documents FOR SELECT TO authenticated USING (true);")

    op.execute("ALTER TABLE document_chunks ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY chunks_read_policy ON document_chunks FOR SELECT TO authenticated USING (true);")


def downgrade() -> None:
    """Downgrade schema."""
    # Disable RLS policies
    op.execute("DROP POLICY IF EXISTS chunks_read_policy ON document_chunks;")
    op.execute("DROP POLICY IF EXISTS documents_read_policy ON source_documents;")
    op.execute("DROP POLICY IF EXISTS citation_message_user_policy ON message_citations;")
    op.execute("DROP POLICY IF EXISTS message_thread_user_policy ON chat_messages;")
    op.execute("DROP POLICY IF EXISTS thread_user_policy ON chat_threads;")
    op.execute("DROP POLICY IF EXISTS user_self_policy ON users;")

    op.execute("ALTER TABLE document_chunks DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE source_documents DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE message_citations DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_messages DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE chat_threads DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY;")

    # Drop indexes and tables
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_chunk_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_document_chunks_metadata_gin', table_name='document_chunks')
    op.drop_index('ix_document_chunks_search_vector_gin', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_documents_ticker'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_fiscal_year'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_filing_type'), table_name='source_documents')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
